### PR TITLE
Replaced Chinese symbols by common ones

### PR DESCRIPTION
**Pull request by adrienluitot**
-, + and = where Chinese symbol. So other users had issues with the fonts.
I replaced the Chinese symbols by the "normal" ones.

Should fix this issue #28 and this one https://github.com/linuxdeepin/developer-center/issues/1417
and this card : https://github.com/orgs/linuxdeepin/projects/1#card-24196492

### CODE REVIEW

**Comment by adrienluitot** [comment]
@BLumia Can you do something ?

**Comment by BLumia** [comment]
> @BLumia Can you do something ?

Sorry I don't maintain this project so I cannot help you get this patch merge :(

btw there is a v20 release which the whole team is working on but the source may not sync back on GitHub before the final v20 release.

If you are using Arch, maybe you can create a fork and maintain an AUR for your patched version so others can get benefit on your patch :)

**Comment by adrienluitot** [comment]
Oh okay I'll wait, it's pity that there is no update / information about it.

Hmm I don't think I'll do a fork on git but thanks for the advice ;)

**Comment by z966768** [comment]
First of all, I am very sorry to reply very late, and then the +, = symbols use Chinese symbols is determined by design, so we can not modify, we will consider your suggestions later, thank you very much

**Comment by BLumia** [comment]
It's a design decision made by the designer, so I'm afraid it could not be merged. I'll close this one for now.

Thanks again for the contribution. You can maintain a fork that doesn't replace these symbols if you like :)

**Pull request closed without merging**
