### PR TITLE
fix: 修复焦点异常问题

### PR DESCRIPTION
**Pull request by pengfeixx**
更改窗口属性后重新设置焦点

Bug: https://pms.uniontech.com/bug-view-162597.html
Log: 修复部分已知问题

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
