### PR TITLE
fix: 修复十六进制粘贴问题

### PR DESCRIPTION
**Pull request by pengfeixx**
将文本转为大写再进行过滤

Bug: https://pms.uniontech.com/bug-view-160445.html
Log: 修复部分已知问题

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
